/* Generated by materialize_syscall_batch.py */
#include <errno.h>
#include <stdio.h>
#include <unistd.h>
#include <sys/syscall.h>

int main(void)
{
	errno = 0;
	long r = syscall(SYS_copy_file_range, -1, NULL, -1, NULL, 0, 0);
	int e = errno;
	dprintf(1, "CASE copy_file_range.badfd ret=%ld errno=%d note=handwritten\n", (long)r, e);
	return 0;
}

