/* Generated by materialize_syscall_batch.py */
#include <errno.h>
#include <stdio.h>
#include <sys/syscall.h>
#include <unistd.h>

int main(void)
{
	errno = 0;
	long r = syscall(SYS_fadvise64, -1, 0, 0, 0);
	int e = errno;
	dprintf(1, "CASE fadvise64.badfd ret=%ld errno=%d note=handwritten\n", (long)r, e);
	return 0;
}

