/* Generated by materialize_syscall_batch.py */
#include <errno.h>
#include <stdio.h>
#include <sys/file.h>

int main(void)
{
	errno = 0;
	int r = flock(-1, LOCK_EX);
	int e = errno;
	dprintf(1, "CASE flock.badfd ret=%ld errno=%d note=handwritten\n", (long)r, e);
	return 0;
}

