/* Generated by materialize_syscall_batch.py */
#include <errno.h>
#include <stdio.h>
#include <unistd.h>

int main(void)
{
	errno = 0;
	int r = fsync(-1);
	int e = errno;
	dprintf(1, "CASE fsync.badfd ret=%ld errno=%d note=handwritten\n", (long)r, e);
	return 0;
}

