/* Generated by materialize_syscall_batch.py */
#include <errno.h>
#include <stdio.h>
#include <sys/uio.h>
#include <unistd.h>

int main(void)
{
	errno = 0;
	char b; struct iovec iov = { &b, 1 }; ssize_t r = preadv(-1, &iov, 1, 0);
	int e = errno;
	dprintf(1, "CASE preadv.badfd ret=%ld errno=%d note=handwritten\n", (long)r, e);
	return 0;
}

