/* Generated by materialize_syscall_batch.py */
#include <errno.h>
#include <stdio.h>
#include <sys/uio.h>
#include <sys/syscall.h>
#include <unistd.h>

int main(void)
{
	errno = 0;
	char b; struct iovec iov = { &b, 1 }; long r = syscall(SYS_preadv2, -1, &iov, 1, 0, 0);
	int e = errno;
	dprintf(1, "CASE preadv2.badfd ret=%ld errno=%d note=handwritten\n", (long)r, e);
	return 0;
}

