/* Generated by materialize_syscall_batch.py */
#include <errno.h>
#include <stdio.h>
#include <sys/sendfile.h>

int main(void)
{
	errno = 0;
	ssize_t r = sendfile(-1, -1, NULL, 0);
	int e = errno;
	dprintf(1, "CASE sendfile.badfd ret=%ld errno=%d note=handwritten\n", (long)r, e);
	return 0;
}

